### ISSUE TITLE
Resampling with SOX 

### ISSUE THREAD

**Issue by kovalroma** [qualitymanifest/timestampSDR#5]
Hello, 
I want to run **rtl_fm** with 8kHz, but timestampSDR needed 48kHz input. You advice to resample with ``` -s <whatever> -r 48k ``` options. But in this case I catch an error. Moreover [keenerd](http://kmkeen.com/rtl-demod-guide/2014-01-24-03-21-57-580.html) wrote ``` using -r option  is also a very poor quality resampler. Use sox for resampling.``` 

Have you tried to use **sox** to resample ? Can you give an advice how to make proper pipeline?

**Comment by qualitymanifest** [comment]
I think the problem is that rtl_fm doesn't support upsampling, only downsampling. There might be a way to achieve that with sox, but your best option is probably to modify [this line](https://github.com/qualitymanifest/timestampSDR/blob/c7613efed9892b16a9084769cee659d03f77483d/imports/create_file.js#L15) to use `8000` instead of `48000`, and then you can use `-s 8k` in your rtl_fm command without resampling. If you give that a try let me know if it works, I imagine it should

**Comment by kovalroma** [comment]
It works! Thank you !

**Comment by kovalroma** [comment]
I propose to add this parameter (**sampleRate**) to **config.js**.

**Comment by qualitymanifest** [comment]
Yeah that sounds like a good idea, I'll add it in when I get a chance

**Comment by qualitymanifest** [comment]
Added sampleRate parameter in 03134ca

**Comment by kovalroma** [comment]
Hi, 
@qualitymanifest  I've checked your new code and I feel that something wrong :)
I've changed ``` sampleRate ``` in ``` config.js ``` to ``` 8000 ``` but program saved file with ``` 44100 ```

Can you check please?

**Comment by kovalroma** [comment]
Here some screenshots: 
![Screenshot_135](https://user-images.githubusercontent.com/20167720/85790075-ee71c200-b72f-11ea-90d2-7d0554363850.png)
![Screenshot_136](https://user-images.githubusercontent.com/20167720/85790084-f2054900-b72f-11ea-9912-75fe070a7d28.png)

**Comment by qualitymanifest** [comment]
~~Ah, I hadn't thought about this. timestampSDR uses node-wav for creating wav files, and regardless of what input rate you provide, I guess it [writes at 44100](https://github.com/TooTallNate/node-wav/blob/a7f9fd33909321a8c1212cc87d6c03223923cad4/lib/writer.js#L71). I'll look into this more this weekend~~

**Comment by qualitymanifest** [comment]
@kovalroma I was way off, `node-wav` is definitely _not_ hardcoded to use 44100, it uses the sample rate you provide and I was providing it an `undefined` sample rate. Whoops! Sorry about that. Anyway I just pushed up a few commits that should fix that, and also added the option to specify `channels` and `bitDepth`

**Comment by kovalroma** [comment]
@qualitymanifest  hey, still have an issue with default settings.

``` 
pi@raspberrypi:~/timestampSDR $ node main.js 
/home/pi/timestampSDR/src/handle_options.js:54
	if (key === "sampleRate" && isNumInvalid({ num: val, min: 1, max: 4_300_000_000, isInt: true, })) {
	                                                                  ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/timestampSDR/main.js:3:23)
```

**Comment by kovalroma** [comment]
I think this is incorrect

https://github.com/qualitymanifest/timestampSDR/blob/master/src/handle_options.js#L54

Should be 
``` 
if (key === "sampleRate" && isNumInvalid({ num: val, min: 1, max: 4300000000, isInt: true, })) {
		return wasInvalid(option, key, "Must be an integer between 1 and 4300000000");
```
?

**Comment by qualitymanifest** [comment]
That is using [numeric separators](https://v8.dev/features/numeric-separators), which were apparently introduced in Node 12.5.0 - I thought they had been around for longer than that, this was my first time using them. Since they're just for developer convenience, there's no sense in breaking support for older versions of Node just for that, so I just pushed a commit removing them. Should be good now, let me know if you have any other issues
